### ISSUE TITLE
Rad Dropdowns don't close on background tap on mobile

### ISSUE THREAD

**Issue by evrowe** [healthsparq/ember-radical#42]
## Summary
Rad Dropdowns inherited this problem from uicore's `core-dropdown`; we need to add `cursor: pointer;` to the structural styles for the background element styling so that taps are still registered and fire Ember action handlers:

```scss
.rad-dropdown-background { // this is the className post namespace change
  @media only screen and (max-width: 40.063em) {
    cursor: pointer;
  }
}
```

## Description + Repro Steps
This is how I found this issue and these steps reliably cause it to occur:

1. View the dummy app on a smartphone/small screen device (emulating in Chrome dev tools works)
2. Open a rad-dropdown instance
3. Try to tap anywhere else on the page outside of the dropdown
4. The dropdown doesn't close. This works as expected on desktops/not touch screen devices.
